=== ldposavec/Java2-Cartographers/xml/dtd/gameMoves.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT GameMoves (GameMove+)>
        <!ELEMENT GameMove (TurnCount, Season, PositionX, PositionY, CoinCount)>
        <!--<!ELEMENT GameMove (TurnCount, Season, PositionX, PositionY, CoinCount, Points)>-->
        <!ELEMENT TurnCount (#PCDATA)>
        <!ELEMENT Season (#PCDATA)>
        <!ELEMENT PositionX (#PCDATA)>
        <!ELEMENT PositionY (#PCDATA)>
        <!ELEMENT CoinCount (#PCDATA)>
        <!--<!ELEMENT Points (#PCDATA)>-->

=== ldposavec/Java2-Cartographers/xml/gameMoves.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE GameMoves SYSTEM "dtd/gameMoves.dtd">
<GameMoves>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SPRING</Season>
        <PositionX>1</PositionX>
        <PositionY>3</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>SPRING</Season>
        <PositionX>1</PositionX>
        <PositionY>6</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>SPRING</Season>
        <PositionX>6</PositionX>
        <PositionY>3</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>0</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>6</PositionX>
        <PositionY>6</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SPRING</Season>
        <PositionX>2</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>SPRING</Season>
        <PositionX>4</PositionX>
        <PositionY>1</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>SPRING</Season>
        <PositionX>3</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>0</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>2</PositionX>
        <PositionY>1</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>3</PositionX>
        <PositionY>0</PositionY>
        <CoinCount>1</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>7</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>1</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>8</PositionX>
        <PositionY>1</PositionY>
        <CoinCount>1</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>0</TurnCount>
        <Season>FALL</Season>
        <PositionX>0</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>1</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>FALL</Season>
        <PositionX>8</PositionX>
        <PositionY>3</PositionY>
        <CoinCount>2</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>FALL</Season>
        <PositionX>3</PositionX>
        <PositionY>7</PositionY>
        <CoinCount>2</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>FALL</Season>
        <PositionX>6</PositionX>
        <PositionY>6</PositionY>
        <CoinCount>2</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>0</TurnCount>
        <Season>WINTER</Season>
        <PositionX>6</PositionX>
        <PositionY>9</PositionY>
        <CoinCount>2</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>WINTER</Season>
        <PositionX>0</PositionX>
        <PositionY>6</PositionY>
        <CoinCount>2</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>WINTER</Season>
        <PositionX>6</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>2</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>WINTER</Season>
        <PositionX>1</PositionX>
        <PositionY>1</PositionY>
        <CoinCount>2</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SPRING</Season>
        <PositionX>1</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>SPRING</Season>
        <PositionX>5</PositionX>
        <PositionY>3</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>SPRING</Season>
        <PositionX>4</PositionX>
        <PositionY>8</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>0</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>0</PositionX>
        <PositionY>6</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SPRING</Season>
        <PositionX>2</PositionX>
        <PositionY>3</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>1</TurnCount>
        <Season>SPRING</Season>
        <PositionX>1</PositionX>
        <PositionY>3</PositionY>
        <CoinCount>1</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SPRING</Season>
        <PositionX>3</PositionX>
        <PositionY>3</PositionY>
        <CoinCount>2</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>3</TurnCount>
        <Season>SPRING</Season>
        <PositionX>5</PositionX>
        <PositionY>3</PositionY>
        <CoinCount>3</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SPRING</Season>
        <PositionX>0</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>SPRING</Season>
        <PositionX>1</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>SPRING</Season>
        <PositionX>2</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>8</TurnCount>
        <Season>SPRING</Season>
        <PositionX>3</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>0</TurnCount>
        <Season>SPRING</Season>
        <PositionX>4</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>1</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>1</PositionX>
        <PositionY>5</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>3</PositionX>
        <PositionY>4</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>3</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>7</PositionX>
        <PositionY>6</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>4</PositionX>
        <PositionY>8</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>5</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>7</PositionX>
        <PositionY>8</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>8</PositionX>
        <PositionY>10</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>7</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>1</PositionX>
        <PositionY>10</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>8</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>6</PositionX>
        <PositionY>1</PositionY>
        <CoinCount>1</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>0</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>0</PositionX>
        <PositionY>7</PositionY>
        <CoinCount>2</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SPRING</Season>
        <PositionX>0</PositionX>
        <PositionY>0</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>SPRING</Season>
        <PositionX>0</PositionX>
        <PositionY>2</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>SPRING</Season>
        <PositionX>0</PositionX>
        <PositionY>4</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>0</TurnCount>
        <Season>SPRING</Season>
        <PositionX>0</PositionX>
        <PositionY>8</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>5</PositionX>
        <PositionY>1</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>4</PositionX>
        <PositionY>3</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>6</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>4</PositionX>
        <PositionY>6</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>0</TurnCount>
        <Season>SUMMER</Season>
        <PositionX>7</PositionX>
        <PositionY>4</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>2</TurnCount>
        <Season>SPRING</Season>
        <PositionX>0</PositionX>
        <PositionY>0</PositionY>
        <CoinCount>0</CoinCount>
    </GameMove>
    <GameMove>
        <TurnCount>4</TurnCount>
        <Season>SPRING</Season>
        <PositionX>1</PositionX>
